# Generated by Django 4.0.2 on 2022-02-19 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=300)),
                ('mode', models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ngo')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_chosen', models.CharField(max_length=10)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supportgroup.groupevent')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
