# Generated by Django 4.0.2 on 2022-02-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Visually Imapired', 'Visually Imapired'), ('Physically impaired', 'Physically impaired'), ('Hearing impaired', 'Hearing impaired'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
